services:
  api:
    build: ./backend
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  web:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: ["bash", "-lc", "npm install && npm run dev -- --host"]
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api
